"""Block decode conformance tests — decode + re-hash vs Ogmios.

VNODE-158: Fetch blocks from the Docker Compose Ogmios instance (connected
to a Haskell cardano-node on preprod), decode them with our block header
decoder, and verify hashes match what Ogmios reports.

Architecture:
  Block CBOR fixtures are generated by generate_fixtures.py which connects
  to the cardano-node via the N2C local chain-sync mini-protocol and queries
  Ogmios for block metadata (hash, era, tx count) as the oracle of truth.
  Tests decode the fixture CBOR with our block header decoder and verify
  correctness against the Ogmios-reported values.

Spec references:
  - shelley.cddl: block, header, header_body
  - babbage.cddl: header_body (vrf_result replaces nonce_vrf + leader_vrf)
  - Hard-fork combinator era tags: 0=Byron main, 1=Byron EBB, 2=Shelley,
    3=Allegra, 4=Mary, 5=Alonzo, 6=Babbage, 7=Conway

Test specifications consulted (from test_specifications table):
  - test_byron_block_roundtrip_main / test_byron_block_roundtrip_ebb
  - test_blockproof_cbor_roundtrip
  - test_send_uses_serialised_receive_deserialises
  - test_constr_encoding_matches_haskell_golden_vectors
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
import websockets

from vibe.cardano.serialization.block import (
    BlockHeader,
    Era,
    block_hash,
    decode_block_header,
    detect_era,
)


# ---------------------------------------------------------------------------
# Fixture loading
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "blocks"

SKIP_MSG = (
    "No block CBOR fixtures found. Generate them with:\n"
    "  docker run --rm \\\n"
    "    -v vibe-node_cardano-node-ipc:/ipc:ro \\\n"
    "    -v $(pwd)/tests/conformance:/tests/conformance \\\n"
    "    -v $(pwd)/packages/vibe-cardano/src:/src \\\n"
    "    -e PYTHONPATH=/src \\\n"
    "    --network vibe-node_vibe-node \\\n"
    "    python:3.14-slim \\\n"
    '    bash -c "pip install cbor2 websockets && '
    'python3 /tests/conformance/generate_fixtures.py"'
)


def _load_fixtures() -> list[dict[str, Any]]:
    """Load block CBOR fixtures from disk.

    Each fixture is a JSON file with:
      {
        "slot": int,
        "hash": str (hex),
        "era": str,
        "height": int,
        "tx_count": int,
        "cbor": str (hex-encoded tagged block CBOR)
      }
    """
    if not FIXTURE_DIR.exists():
        return []
    fixtures = []
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        with open(path) as f:
            data = json.load(f)
            if data.get("cbor"):  # Only include fixtures with CBOR
                fixtures.append(data)
    return fixtures


def _era_name_to_enum(era_name: str) -> Era | None:
    """Map Ogmios era name string to our Era enum."""
    mapping = {
        "byron": Era.BYRON_MAIN,
        "shelley": Era.SHELLEY,
        "allegra": Era.ALLEGRA,
        "mary": Era.MARY,
        "alonzo": Era.ALONZO,
        "babbage": Era.BABBAGE,
        "conway": Era.CONWAY,
    }
    return mapping.get(era_name.lower() if era_name else "")


# ---------------------------------------------------------------------------
# Ogmios chain-sync helpers
# ---------------------------------------------------------------------------

async def _ogmios_chain_sync_blocks(
    ogmios_url: str, max_blocks: int = 10, max_walk: int = 6000
) -> list[dict[str, Any]]:
    """Walk from origin via Ogmios chain-sync and collect post-Byron blocks."""
    blocks: list[dict[str, Any]] = []

    async with websockets.connect(ogmios_url) as ws:
        await ws.send(json.dumps({
            "jsonrpc": "2.0",
            "method": "findIntersection",
            "params": {"points": ["origin"]},
            "id": "sync-start",
        }))
        resp = json.loads(await ws.recv())
        if "error" in resp:
            raise RuntimeError(f"findIntersection error: {resp['error']}")

        for _ in range(max_walk):
            await ws.send(json.dumps({
                "jsonrpc": "2.0",
                "method": "nextBlock",
                "id": "next",
            }))
            resp = json.loads(await ws.recv())
            result = resp.get("result", {})
            direction = result.get("direction")

            if direction == "backward":
                continue
            elif direction == "forward":
                block = result.get("block")
                if block is not None and isinstance(block, dict):
                    era = (block.get("era") or "").lower()
                    if era != "byron":
                        blocks.append(block)
                        if len(blocks) >= max_blocks:
                            break
            else:
                break

    return blocks


async def _ogmios_chain_sync_by_era(
    ogmios_url: str, max_walk: int = 20_000
) -> dict[str, dict[str, Any]]:
    """Walk from origin and collect the first block from each post-Byron era."""
    era_blocks: dict[str, dict[str, Any]] = {}
    era_order = ["shelley", "allegra", "mary", "alonzo", "babbage", "conway"]

    async with websockets.connect(ogmios_url) as ws:
        await ws.send(json.dumps({
            "jsonrpc": "2.0",
            "method": "findIntersection",
            "params": {"points": ["origin"]},
            "id": "era-sync",
        }))
        resp = json.loads(await ws.recv())
        if "error" in resp:
            return era_blocks

        for _ in range(max_walk):
            if len(era_blocks) >= len(era_order):
                break

            await ws.send(json.dumps({
                "jsonrpc": "2.0",
                "method": "nextBlock",
                "id": "era-walk",
            }))
            resp = json.loads(await ws.recv())
            result = resp.get("result", {})

            if result.get("direction") != "forward":
                continue

            block = result.get("block")
            if block is None or not isinstance(block, dict):
                continue

            era = (block.get("era") or "").lower()
            if era in era_order and era not in era_blocks:
                era_blocks[era] = block

    return era_blocks


# ---------------------------------------------------------------------------
# Test 1: Decode recent blocks (fixture-based)
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(30)
async def test_decode_recent_blocks() -> None:
    """Decode block CBOR fixtures, verify valid BlockHeader objects.

    Validates that our decoder handles real chain data across eras:
    - decode_block_header returns a valid BlockHeader
    - Slot numbers match fixture metadata
    - Block numbers are positive
    - Era matches fixture metadata
    - Issuer vkey is 32 bytes (Ed25519)
    - Block body hash is 32 bytes (Blake2b-256)
    - Protocol version major >= 2 for all post-Byron blocks
    """
    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip(SKIP_MSG)

    decoded_count = 0

    for fixture in fixtures:
        cbor_bytes = bytes.fromhex(fixture["cbor"])
        expected_slot = fixture["slot"]
        expected_era = fixture.get("era", "").lower()

        header = decode_block_header(cbor_bytes)

        assert isinstance(header, BlockHeader), (
            f"Expected BlockHeader, got {type(header).__name__}"
        )
        assert header.slot == expected_slot, (
            f"Slot mismatch: decoder={header.slot}, fixture={expected_slot}"
        )
        assert header.block_number > 0, (
            f"Block number should be > 0, got {header.block_number}"
        )

        if expected_era:
            expected_enum = _era_name_to_enum(expected_era)
            if expected_enum is not None:
                assert header.era == expected_enum, (
                    f"Era mismatch at slot {expected_slot}: "
                    f"decoder={header.era.name}, fixture={expected_era}"
                )

        assert len(header.issuer_vkey) == 32, (
            f"Issuer vkey should be 32 bytes, got {len(header.issuer_vkey)}"
        )
        assert len(header.block_body_hash) == 32, (
            f"Block body hash should be 32 bytes, got {len(header.block_body_hash)}"
        )
        assert header.protocol_version.major >= 2, (
            f"Protocol major should be >= 2, got {header.protocol_version.major}"
        )

        decoded_count += 1

    assert decoded_count >= 1, f"Decoded {decoded_count} blocks"


# ---------------------------------------------------------------------------
# Test 2: Block hash matches Ogmios
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(30)
async def test_block_hash_matches_ogmios() -> None:
    """Compute block_hash from our decoder, compare against Ogmios-reported hash.

    The block hash is Blake2b-256 of the CBOR-encoded header. The fixture
    records the hash from Ogmios (the Haskell node's oracle truth). If our
    hash doesn't match, our header extraction or CBOR re-encoding is wrong.

    This is the CRITICAL conformance check for the block decoder.

    Spec: block hash = Blake2b-256(header_cbor) where header_cbor is the
    serialized [header_body, body_signature] array.
    """
    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip(SKIP_MSG)

    verified_count = 0

    for fixture in fixtures:
        cbor_bytes = bytes.fromhex(fixture["cbor"])
        expected_hash = fixture["hash"]

        if not expected_hash:
            continue  # No Ogmios hash available

        header = decode_block_header(cbor_bytes)
        our_hash = header.hash.hex()

        assert our_hash == expected_hash, (
            f"Block hash mismatch at slot {header.slot}!\n"
            f"  Our hash:    {our_hash}\n"
            f"  Ogmios hash: {expected_hash}\n"
            f"  Era: {header.era.name}\n"
            f"  Block number: {header.block_number}\n"
            f"  Header CBOR length: {len(header.header_cbor)} bytes"
        )

        verified_count += 1

    assert verified_count >= 1, f"Verified {verified_count} block hashes"


# ---------------------------------------------------------------------------
# Test 3: Multi-era decode
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(30)
async def test_multi_era_decode() -> None:
    """Verify blocks from different eras decode correctly.

    Validates structural differences across eras:
    - Shelley-Alonzo: two VRF certs (nonce_vrf + leader_vrf), 15+ header fields
    - Babbage-Conway: single vrf_result, 14+ header fields

    Must decode at least 2 different eras to pass.
    """
    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip(SKIP_MSG)

    eras_decoded: set[str] = set()

    for fixture in fixtures:
        cbor_bytes = bytes.fromhex(fixture["cbor"])
        expected_era = fixture.get("era", "").lower()

        header = decode_block_header(cbor_bytes)
        assert isinstance(header, BlockHeader)

        expected_enum = _era_name_to_enum(expected_era)
        if expected_enum is not None:
            assert header.era == expected_enum, (
                f"Era mismatch for {expected_era}: decoder={header.era.name}"
            )

        assert header.slot > 0
        assert header.block_number > 0
        assert len(header.issuer_vkey) == 32
        assert len(header.block_body_hash) == 32

        eras_decoded.add(header.era.name)

    assert len(eras_decoded) >= 2, (
        f"Expected >= 2 eras decoded, got: {sorted(eras_decoded)}"
    )


# ---------------------------------------------------------------------------
# Test 4: Transaction count matches
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(30)
async def test_transaction_count_matches() -> None:
    """Decode full block body, count transactions, compare against Ogmios.

    Block CDDL structure:
      block = [header, transaction_bodies, transaction_witness_sets, auxiliary_data_set]
      transaction_bodies = [* transaction_body]  (CBOR array)

    The fixture records the tx count from Ogmios.
    """
    from vibe.cardano.serialization.block import _strip_tag, _loads

    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip(SKIP_MSG)

    verified_count = 0

    for fixture in fixtures:
        expected_tx_count = fixture.get("tx_count")
        if expected_tx_count is None:
            continue

        cbor_bytes = bytes.fromhex(fixture["cbor"])
        _tag, payload = _strip_tag(cbor_bytes)
        block_array = _loads(payload)

        if not isinstance(block_array, list) or len(block_array) < 4:
            continue

        tx_bodies = block_array[1]

        if isinstance(tx_bodies, (list, dict)):
            our_tx_count = len(tx_bodies)
        else:
            continue

        assert our_tx_count == expected_tx_count, (
            f"TX count mismatch at slot {fixture['slot']}!\n"
            f"  Our count:    {our_tx_count}\n"
            f"  Ogmios count: {expected_tx_count}\n"
            f"  Era: {fixture.get('era')}"
        )

        verified_count += 1

    assert verified_count >= 1, f"Verified {verified_count} tx counts"


# ---------------------------------------------------------------------------
# Test 5: Era detection consistency
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(30)
async def test_era_detection_matches_decode() -> None:
    """Verify detect_era() and decode_block_header() agree on era.

    detect_era() reads only the CBOR tag byte without decoding the block.
    decode_block_header() fully decodes the header. They must report the
    same era for every block.
    """
    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip(SKIP_MSG)

    for fixture in fixtures:
        cbor_bytes = bytes.fromhex(fixture["cbor"])
        detected_era = detect_era(cbor_bytes)
        header = decode_block_header(cbor_bytes)

        assert detected_era == header.era, (
            f"Era inconsistency at slot {header.slot}: "
            f"detect_era={detected_era.name}, "
            f"decode_block_header={header.era.name}"
        )


# ---------------------------------------------------------------------------
# Test 6: Block hash deterministic
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(30)
async def test_block_hash_deterministic() -> None:
    """Verify decoding the same block twice produces the same hash.

    Catches non-determinism in CBOR re-encoding or hash computation.
    The hash must be identical across multiple decode passes.
    """
    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip(SKIP_MSG)

    for fixture in fixtures:
        cbor_bytes = bytes.fromhex(fixture["cbor"])

        header1 = decode_block_header(cbor_bytes)
        header2 = decode_block_header(cbor_bytes)

        assert header1.hash == header2.hash, (
            f"Non-deterministic hash at slot {header1.slot}: "
            f"{header1.hash.hex()} != {header2.hash.hex()}"
        )
        assert header1.header_cbor == header2.header_cbor, (
            f"Non-deterministic header CBOR at slot {header1.slot}"
        )


# ---------------------------------------------------------------------------
# Test 7: Ogmios block metadata validation (live, no CBOR needed)
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(120)
async def test_ogmios_block_metadata(ogmios_url: str) -> None:
    """Validate block metadata from Ogmios chain-sync (live test).

    Works without CBOR fixtures — validates Ogmios JSON responses:
    - Each block has a slot number > 0
    - Each block has a 64-char hex block hash
    - Each block has a known era name
    - Block heights are monotonically increasing
    - Transactions field is a list
    """
    blocks = await _ogmios_chain_sync_blocks(ogmios_url, max_blocks=10)
    assert len(blocks) > 0, "Expected at least 1 post-Byron block from Ogmios"

    valid_eras = {"shelley", "allegra", "mary", "alonzo", "babbage", "conway"}
    prev_height = -1

    for block in blocks:
        slot = block.get("slot")
        assert isinstance(slot, int) and slot > 0, f"Invalid slot: {slot}"

        block_id = block.get("id")
        assert isinstance(block_id, str) and len(block_id) == 64, (
            f"Invalid block hash: {block_id}"
        )
        bytes.fromhex(block_id)  # Verify valid hex

        era = (block.get("era") or "").lower()
        assert era in valid_eras, f"Unknown era '{era}' at slot {slot}"

        height = block.get("height")
        if isinstance(height, int):
            assert height > prev_height, (
                f"Heights not monotonically increasing: {height} <= {prev_height}"
            )
            prev_height = height

        txs = block.get("transactions")
        assert isinstance(txs, list), (
            f"Transactions should be a list at slot {slot}"
        )


# ---------------------------------------------------------------------------
# Test 8: Multi-era via Ogmios (live, supplements CBOR fixture test)
# ---------------------------------------------------------------------------

@pytest.mark.conformance
@pytest.mark.timeout(600)
async def test_multi_era_ogmios(ogmios_url: str) -> None:
    """Walk Ogmios chain-sync and verify multiple eras exist on preprod.

    This live test validates that preprod has gone through multiple hard
    forks and our Ogmios chain-sync walk correctly identifies era transitions.
    Must find at least 2 different eras.
    """
    era_blocks = await _ogmios_chain_sync_by_era(ogmios_url)

    for era_name, block in era_blocks.items():
        assert block.get("era", "").lower() == era_name
        assert isinstance(block.get("slot"), int)
        assert isinstance(block.get("id"), str)

    assert len(era_blocks) >= 2, (
        f"Expected >= 2 eras from Ogmios, got: {sorted(era_blocks.keys())}"
    )
