/**
 * _vrf_native — pybind11 bindings for IOG libsodium VRF functions.
 *
 * Wraps the ECVRF-ED25519-SHA512-Elligator2 (draft-irtf-cfrg-vrf-03)
 * functions from the IOG fork of libsodium. Cardano uses this VRF
 * construction for Ouroboros Praos leader election.
 *
 * Spec references:
 *   - draft-irtf-cfrg-vrf-03 (ECVRF construction)
 *   - Ouroboros Praos paper, Section 4 (leader election)
 *   - Haskell: Cardano.Crypto.VRF.Praos
 *
 * The IOG libsodium fork adds crypto_vrf_ietfdraft03_* functions that
 * are not present in stock libsodium.
 */

#include <pybind11/pybind11.h>
#include <sodium.h>
#include <stdexcept>
#include <string>

namespace py = pybind11;

// ---------------------------------------------------------------------------
// Size constants from the IOG libsodium headers
// ---------------------------------------------------------------------------

static constexpr size_t VRF_PROOF_SIZE = crypto_vrf_ietfdraft03_BYTES;           // 80
static constexpr size_t VRF_OUTPUT_SIZE = crypto_vrf_ietfdraft03_OUTPUTBYTES;    // 64
static constexpr size_t VRF_PK_SIZE = crypto_vrf_ietfdraft03_PUBLICKEYBYTES;     // 32
static constexpr size_t VRF_SK_SIZE = crypto_vrf_ietfdraft03_SECRETKEYBYTES;     // 64
static constexpr size_t VRF_SEED_SIZE = crypto_vrf_ietfdraft03_SEEDBYTES;        // 32

// ---------------------------------------------------------------------------
// Helper: ensure sodium_init() has been called
// ---------------------------------------------------------------------------

static void ensure_sodium_init() {
    static bool initialized = false;
    if (!initialized) {
        if (sodium_init() < 0) {
            throw std::runtime_error("sodium_init() failed");
        }
        initialized = true;
    }
}

// ---------------------------------------------------------------------------
// VRF key generation
// ---------------------------------------------------------------------------

/**
 * Generate a VRF keypair using a random seed.
 *
 * Returns a tuple of (public_key: bytes[32], secret_key: bytes[64]).
 *
 * Uses crypto_vrf_ietfdraft03_keypair_from_seed with a random seed
 * generated by libsodium's CSPRNG (randombytes_buf).
 */
static py::tuple vrf_keypair() {
    ensure_sodium_init();

    unsigned char pk[VRF_PK_SIZE];
    unsigned char sk[VRF_SK_SIZE];
    unsigned char seed[VRF_SEED_SIZE];

    // Generate a cryptographically secure random seed.
    randombytes_buf(seed, VRF_SEED_SIZE);

    int rc = crypto_vrf_ietfdraft03_keypair_from_seed(pk, sk, seed);
    // Wipe the seed from memory immediately.
    sodium_memzero(seed, VRF_SEED_SIZE);

    if (rc != 0) {
        throw std::runtime_error("crypto_vrf_ietfdraft03_keypair_from_seed failed");
    }

    return py::make_tuple(
        py::bytes(reinterpret_cast<const char*>(pk), VRF_PK_SIZE),
        py::bytes(reinterpret_cast<const char*>(sk), VRF_SK_SIZE)
    );
}

// ---------------------------------------------------------------------------
// VRF prove
// ---------------------------------------------------------------------------

/**
 * Generate a VRF proof for the given message (alpha string).
 *
 * Parameters:
 *   sk: Secret key (64 bytes)
 *   alpha: Input message (arbitrary length)
 *
 * Returns: VRF proof (80 bytes)
 *
 * Raises RuntimeError if the prove operation fails.
 */
static py::bytes vrf_prove(py::bytes sk, py::bytes alpha) {
    ensure_sodium_init();

    std::string sk_str = sk;
    std::string alpha_str = alpha;

    if (sk_str.size() != VRF_SK_SIZE) {
        throw py::value_error(
            "VRF secret key must be " + std::to_string(VRF_SK_SIZE) +
            " bytes, got " + std::to_string(sk_str.size())
        );
    }

    unsigned char proof[VRF_PROOF_SIZE];

    int rc = crypto_vrf_ietfdraft03_prove(
        proof,
        reinterpret_cast<const unsigned char*>(sk_str.data()),
        reinterpret_cast<const unsigned char*>(alpha_str.data()),
        static_cast<unsigned long long>(alpha_str.size())
    );

    if (rc != 0) {
        throw std::runtime_error("crypto_vrf_ietfdraft03_prove failed");
    }

    return py::bytes(reinterpret_cast<const char*>(proof), VRF_PROOF_SIZE);
}

// ---------------------------------------------------------------------------
// VRF verify
// ---------------------------------------------------------------------------

/**
 * Verify a VRF proof and return the output hash.
 *
 * Parameters:
 *   pk: Public key (32 bytes)
 *   proof: VRF proof (80 bytes)
 *   alpha: Input message (arbitrary length)
 *
 * Returns: VRF output hash (64 bytes)
 *
 * Raises ValueError on incorrect input sizes.
 * Raises RuntimeError if verification fails (invalid proof).
 */
static py::bytes vrf_verify(py::bytes pk, py::bytes proof, py::bytes alpha) {
    ensure_sodium_init();

    std::string pk_str = pk;
    std::string proof_str = proof;
    std::string alpha_str = alpha;

    if (pk_str.size() != VRF_PK_SIZE) {
        throw py::value_error(
            "VRF public key must be " + std::to_string(VRF_PK_SIZE) +
            " bytes, got " + std::to_string(pk_str.size())
        );
    }
    if (proof_str.size() != VRF_PROOF_SIZE) {
        throw py::value_error(
            "VRF proof must be " + std::to_string(VRF_PROOF_SIZE) +
            " bytes, got " + std::to_string(proof_str.size())
        );
    }

    unsigned char output[VRF_OUTPUT_SIZE];

    int rc = crypto_vrf_ietfdraft03_verify(
        output,
        reinterpret_cast<const unsigned char*>(pk_str.data()),
        reinterpret_cast<const unsigned char*>(proof_str.data()),
        reinterpret_cast<const unsigned char*>(alpha_str.data()),
        static_cast<unsigned long long>(alpha_str.size())
    );

    if (rc != 0) {
        throw std::runtime_error(
            "VRF verification failed: invalid proof for the given public key and message"
        );
    }

    return py::bytes(reinterpret_cast<const char*>(output), VRF_OUTPUT_SIZE);
}

// ---------------------------------------------------------------------------
// VRF proof_to_hash
// ---------------------------------------------------------------------------

/**
 * Convert a VRF proof to its output hash without verification.
 *
 * Parameters:
 *   proof: VRF proof (80 bytes)
 *
 * Returns: VRF output hash (64 bytes)
 *
 * WARNING: This does NOT verify the proof. The caller must ensure
 * the proof has already been verified via vrf_verify().
 */
static py::bytes vrf_proof_to_hash(py::bytes proof) {
    ensure_sodium_init();

    std::string proof_str = proof;

    if (proof_str.size() != VRF_PROOF_SIZE) {
        throw py::value_error(
            "VRF proof must be " + std::to_string(VRF_PROOF_SIZE) +
            " bytes, got " + std::to_string(proof_str.size())
        );
    }

    unsigned char hash[VRF_OUTPUT_SIZE];

    int rc = crypto_vrf_ietfdraft03_proof_to_hash(
        hash,
        reinterpret_cast<const unsigned char*>(proof_str.data())
    );

    if (rc != 0) {
        throw std::runtime_error("crypto_vrf_ietfdraft03_proof_to_hash failed");
    }

    return py::bytes(reinterpret_cast<const char*>(hash), VRF_OUTPUT_SIZE);
}

// ---------------------------------------------------------------------------
// Python module definition
// ---------------------------------------------------------------------------

PYBIND11_MODULE(_vrf_native, m) {
    m.doc() = R"doc(
        Native VRF bindings for Ouroboros Praos leader election.

        Wraps the IOG libsodium fork's ECVRF-ED25519-SHA512-Elligator2
        (draft-irtf-cfrg-vrf-03) functions used by Cardano for slot
        leader VRF evaluation.
    )doc";

    // Export size constants so Python can validate without magic numbers.
    m.attr("VRF_PROOF_SIZE") = VRF_PROOF_SIZE;
    m.attr("VRF_OUTPUT_SIZE") = VRF_OUTPUT_SIZE;
    m.attr("VRF_PK_SIZE") = VRF_PK_SIZE;
    m.attr("VRF_SK_SIZE") = VRF_SK_SIZE;
    m.attr("VRF_SEED_SIZE") = VRF_SEED_SIZE;

    m.def("vrf_keypair", &vrf_keypair, R"doc(
        Generate a VRF keypair.

        Returns a tuple (public_key, secret_key) where:
          - public_key is 32 bytes (Ed25519 point)
          - secret_key is 64 bytes (Ed25519 scalar + public key)

        The keypair is generated from a cryptographically secure
        random seed via libsodium's CSPRNG.
    )doc");

    m.def("vrf_prove", &vrf_prove, py::arg("sk"), py::arg("alpha"), R"doc(
        Generate a VRF proof for the given alpha string.

        Parameters:
            sk: VRF secret key (64 bytes)
            alpha: Input message / alpha string (arbitrary length)

        Returns:
            VRF proof (80 bytes)
    )doc");

    m.def("vrf_verify", &vrf_verify,
        py::arg("pk"), py::arg("proof"), py::arg("alpha"), R"doc(
        Verify a VRF proof and return the output hash.

        Parameters:
            pk: VRF public key (32 bytes)
            proof: VRF proof (80 bytes)
            alpha: Input message / alpha string (arbitrary length)

        Returns:
            VRF output hash (64 bytes)

        Raises:
            RuntimeError: If the proof is invalid.
            ValueError: If pk or proof have incorrect sizes.
    )doc");

    m.def("vrf_proof_to_hash", &vrf_proof_to_hash, py::arg("proof"), R"doc(
        Convert a VRF proof to its output hash (without verification).

        Parameters:
            proof: VRF proof (80 bytes)

        Returns:
            VRF output hash (64 bytes)

        WARNING: Does NOT verify the proof. Caller must ensure the
        proof was already verified via vrf_verify().
    )doc");
}
